Add redraw method
karafka/karafka pull request #2345
Opened 2024-11-21 18:38 UTC by dorner

This allows testing code to define its own routes _without_ blowing away the defaults. I've found this helpful when I have overall defaults that I want to keep around, but I want to test my own routing plugin with various routes.

2024-11-22 14:25 UTC, mensfeld requested changes

2024-11-22 14:25 UTC, mensfeld commented on lib/karafka/routing/builder.rb
> +      alias array_clear clear
why 2 names?

2024-11-24 18:50 UTC, mensfeld requested changes

2024-11-24 18:50 UTC, mensfeld commented on lib/karafka/routing/builder.rb
> +      alias array_clear clear
Ah I get it now!

Since it's used internally only could we maybe make it private not to "expose" a false API?

2024-11-25 14:32 UTC, dorner commented
Hmm... I haven't found a good way to do this. `private alias x y` seems to be a syntax error, and the other approaches have caused other problems. Do you know of a way to do this?

2024-11-25 14:36 UTC, dorner commented
Never mind, ChatGPT to the rescue :)

2024-11-25 15:41 UTC, mensfeld approved these changes

2024-11-25 15:41 UTC, merged